fix-workflow-label-search
FRINXio/frinx-frontend pull request #1021
Opened 2022-12-07 14:58 UTC by plehocky

search by label now shows only workflows that include all of the searched labels

https://frinxhelpdesk.atlassian.net/browse/FD-452?atlOrigin=eyJpIjoiOTAyYjRiZDBkYjM0NGRjZmI3Y2IzNGIwZGMxY2YwMzEiLCJwIjoiaiJ9

2022-12-08 12:55 UTC, Paulooze requested changes

2022-12-08 12:55 UTC, Paulooze commented on packages/frinx-workflow-ui/src/pages/workflow-list/workflow-definitions/workflow-definitions.tsx
> +            } else if (labels.length === 1) {
Don't use `else if` - just use another `if` statement (`if (labels.length === 1)`) - and put it before the `> 1` statement.

2022-12-12 14:37 UTC, soson commented on packages/frinx-workflow-ui/src/pages/workflow-list/workflow-definitions/workflow-definitions.tsx
> +            }
is it necessary to have different behaviour based on labels.length? is not enough to just have one:
```
if (labels.length) {
    return labels?.every((label: string) => labelsArr?.includes(label));
}
```

2022-12-12 19:53 UTC, plehocky commented on packages/frinx-workflow-ui/src/pages/workflow-list/workflow-definitions/workflow-definitions.tsx
> +            }
Yes, that also works. Thank you, already made a commit.

2022-12-13 10:00 UTC, merged