updated resource manager UI
FRINXio/frinx-frontend pull request #1053
Opened 2023-01-16 13:52 UTC by plehocky

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-461` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  | No

1) When claiming resource for ipv4_prefix, an input field for desired value is now included and optional 
2) Fixed "There is no record" in first line of "Allocated resources table" in pool detail
3) When creating a pool, pool properties fields are hidden if "Nested" is checked, handled validation
4) Fixed not showing subnet values in pool detail -> allocated resources table
5) Changed placeholder of ipv4 address field

2023-01-18 15:43 UTC, MarcoMruz requested changes
https://github.com/FRINXio/frinx-frontend/blob/19fb00f215a7cd148cb5faec7a7f4d66e8784ea4/packages/frinx-resource-manager/src/pages/pool-detail-page/pool-detail-page.tsx#L168

here you need to define key because it can cause later problem with rerendering calculations and also it throws an error to the console when in development mode

2023-01-18 15:43 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/helpers/create-pool-form.helpers.ts
> +                        }),
you need to handle validation when pool is nested also for other strategies
- try to create e.g. vlan nested pool - currently not possible

2023-01-18 15:43 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/create-pool-page/create-pool-form.tsx
> +
you also need to handle changes when for other strategies

2023-01-23 11:44 UTC, MarcoMruz approved these changes

2023-01-24 09:45 UTC, Paulooze submitted a review, later dismissed

2023-01-24 16:54 UTC, Paulooze approved these changes

2023-01-24 17:02 UTC, MarcoMruz approved these changes

2023-01-25 08:49 UTC, merged