resource manager- strategies and types deletion dialog
FRINXio/frinx-frontend pull request #1065
Opened 2023-01-26 07:27 UTC by plehocky

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-472` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  | No

Dialog shows up when deleting either strategy or resource type, also when deleting a strategy, type is also deleted and same for the opposite case. Dialog contains warning for user informing them that the corresponding strategy/type will be deleted

2023-01-27 06:54 UTC, MarcoMruz requested changes

2023-01-27 06:54 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/components/delete-modal.tsx
> +  propName: string;
not really specific name convention... try to use something more specific for a name (e.g. entityName)

2023-01-27 06:54 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/resource-types-page/resource-types-page.tsx
> +            });
you don't have to use notifications, when just throwing Error would be enough and then handle in catch block the error notification

2023-01-27 06:54 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/resource-types-page/resource-types-page.tsx
> +            });
use more generic error message (e.g. There was a problem with ${entityName} deletion)

2023-01-27 06:54 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/resource-types-page/resource-types-page.tsx
> +    deleteStrategyById(strategyId || '');
you should delete strategy only when deletion of resource type was successfull

2023-01-27 06:54 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/strategies-page/strategies-page.tsx
> +  const deleteResourceTypeById = useCallback(
useCallback is not needed

2023-01-27 06:54 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/resource-types-page/resource-types-page.tsx
> +`;
enough for you is to have id and Name

2023-01-30 10:53 UTC, MarcoMruz requested changes

2023-01-30 10:53 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/strategies-page/strategies-page.tsx
> +  };
make this function as useCallback or move it inside the handleDeleteBtnClick function

2023-01-30 10:53 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/strategies-page/strategies-page.tsx
> +            const resourceTypeById = findResourceTypeId(id);
rename this variable so it clear what it is containing

2023-01-30 10:53 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/strategies-page/strategies-page.tsx
> +            deleteResourceTypeById(resourceTypeById || '');
this function is redundant... you need only to call deleteResourceType function with correct id

also handle if value is empty and show taost notification so that user knows about the problem

2023-01-30 12:04 UTC, MarcoMruz submitted a review, later dismissed

2023-02-01 13:53 UTC, Paulooze submitted a review, later dismissed

2023-02-01 13:53 UTC, Paulooze commented on packages/frinx-resource-manager/src/components/delete-modal.tsx
> +  const getWarningText = (typeName: string) => {
You don't need this function inside the component body.

`typeName` isn't a string in this case, but could be narrowed down to union type (`'strategy'' | 'resource type'`). 

Don't mix return types (`string` and `boolean`).

2023-02-01 13:53 UTC, Paulooze commented on packages/frinx-resource-manager/src/pages/pool-detail-page/pool-detail-page.tsx
> +import DeletePoolPopover from '../../components/delete-modal';
We should stick to matching component name to what's actually exported from the file - `DeleteModal` isn't the same as `DeletePoolPopover`.

2023-02-01 13:53 UTC, Paulooze commented on packages/frinx-resource-manager/src/pages/resource-types-page/resource-types-table.tsx
> +import DeletePopover from '../../components/delete-modal';
Same as above - rename to `DeleteModal`.

2023-02-01 13:53 UTC, Paulooze commented on packages/frinx-resource-manager/src/pages/strategies-page/strategies-table.tsx
> +import DeletePopover from '../../components/delete-modal';
Same as above.

2023-02-03 08:22 UTC, MarcoMruz approved these changes

2023-02-03 08:30 UTC, soson approved these changes

2023-02-03 13:50 UTC, merged