Fix pools table filter
FRINXio/frinx-frontend pull request #1068
Opened 2023-01-27 08:08 UTC by plehocky

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-465` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  | No

https://frinxhelpdesk.atlassian.net/browse/FD-465?atlOrigin=eyJpIjoiNmI4OGYyZDA5MmFhNGRhNmE4MWYxNTE5MmU5Yjk1ZjQiLCJwIjoiaiJ9

Filtering by name was not working unless you opened pool config page and returned with browser back button wich had it cached. Added "items" dependency to useEffect of use-minisearch hook that fixed the issue.

Also fixed filtering by resource type. When selecting for example ipv4, search results were correct but when switching back to default search option no results were listed

2023-01-27 10:41 UTC, MarcoMruz requested changes

2023-01-27 10:41 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/pools-page/pools-page.tsx
> +  const isSelectedResourceTypeEmpty = selectedResourceType === 'Select resource type to filter';
why should you use specific string when we are sending empty value. try to use that empty value

2023-01-30 10:45 UTC, MarcoMruz requested changes

2023-01-30 10:45 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/components/search-filter-pools-bar.tsx
> +            }
do not use specific string value... set empty "" string to the default option in select and use the previous code for handling onChange event `onChange={(e) => setSelectedResourceType && setSelectedResourceType(e.target.value)}`

remove from the default option the onChange event handler - it is unnecessary

2023-01-30 10:45 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/components/search-filter-pools-bar.tsx
> +            <option onChange={() => setSelectedResourceType && setSelectedResourceType('')}>
remove this onChange and use value="" as mentioned in the previous comment

2023-01-30 10:45 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/pools-page/pools-page.tsx
> +  const isSelectedResourceTypeEmpty = selectedResourceType === null || selectedResourceType.trim().length === 0;
use just ==, so that we are able to handle also undefined values

2023-01-30 14:32 UTC, MarcoMruz approved these changes

2023-02-01 08:35 UTC, soson approved these changes

2023-02-01 12:37 UTC, merged