Fix executed wf edit and run bug
FRINXio/frinx-frontend pull request #1113
Opened 2023-02-28 09:21 UTC by plehocky

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-483` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  |

https://frinxhelpdesk.atlassian.net/browse/FD-483?atlOrigin=eyJpIjoiNzQ0ZDYzYmQ5MGU5NDUxZGFkMTRkNjkwYTRmMjliNDMiLCJwIjoiaiJ9

In executed workflows > Edit & run tab the inputs werent displaying values of inputs, neither they could be changed.

HOW TO TEST:

Select any executed workflow and head to edit & run tab, try to change input values and hit Execute button. Values should be displayed and saved.

2023-02-28 13:15 UTC, Paulooze requested changes

2023-02-28 13:15 UTC, Paulooze commented on packages/frinx-workflow-ui/src/pages/executed-workflow-detail/executed-workflow-detail-tabs/edit-rerun-tab.tsx
> +    if (values[i] != null && typeof values[i] === 'string') {
This function doesn't need to exist inside the component body, move it outside.

2023-02-28 13:35 UTC, Paulooze approved these changes

2023-03-01 07:07 UTC, MarcoMruz approved these changes

2023-03-01 07:40 UTC, merged