update decision task type that default case is optional
FRINXio/frinx-frontend pull request #1127
Opened 2023-03-01 11:39 UTC by MarcoMruz

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-485` 
| Tests Added + Pass?      | NO YES
| Any Dependency Changes?  |

When default case of decision task is empty conductor then returns null value for that specific default case. This then creates white screen when user wants to execute workflow. We fix it by making default case optional and handle it accordingly

2023-03-03 08:44 UTC, soson approved these changes

2023-03-06 09:29 UTC, Paulooze requested changes

2023-03-06 09:29 UTC, Paulooze commented on packages/shared/src/helpers/api-to-graph.helpers.ts
> +    const defaultDecisionNodes = createNodes(defaultExtendedTasks || [], isReadOnly); // eslint-disable-line @typescript-eslint/no-use-before-define
Wouldn't `??` be better than `||` - same thing for line 178.

2023-03-08 10:32 UTC, soson approved these changes

2023-03-08 13:16 UTC, Paulooze approved these changes

2023-03-08 13:25 UTC, merged