add strategies page in uniresource; fix prettier
FRINXio/frinx-frontend pull request #115
Opened 2021-06-28 11:39 UTC by Paulooze

Added/edited the strategies page + add strategy form.

2021-06-28 14:13 UTC, MarcoMruz commented on packages/frinx-uniresource-ui/src/pages/strategies-page/strategies-page.tsx
> +  }
What will be rendered when this page returns null?

2021-06-28 14:13 UTC, MarcoMruz commented on packages/frinx-uniresource-ui/src/pages/pools-page/pools-table.tsx
>              const totalCapacity = freeCapacity + utilizedCapacity;
Maybe this could be better if it was written as a function similar to the `getCapacityValue` function... freeCapacity & utilizedCapacity is by default set to 0 value on API?

2021-06-30 08:03 UTC, MarcoMruz submitted a review, later dismissed

2021-06-30 08:46 UTC, Paulooze commented on packages/frinx-uniresource-ui/src/pages/strategies-page/strategies-page.tsx
> +  }
Nothing. `data == null` is basically some kind of error, so it's "handled" in the error check.

2021-06-30 08:46 UTC, Paulooze commented on packages/frinx-uniresource-ui/src/pages/pools-page/pools-table.tsx
>              const totalCapacity = freeCapacity + utilizedCapacity;
Probably, will change it.

2021-06-30 12:43 UTC, MarcoMruz requested changes

2021-06-30 12:43 UTC, MarcoMruz commented on packages/frinx-uniresource-ui/src/pages/pools-page/pools-table.tsx
>              const totalCapacity = freeCapacity + utilizedCapacity;
logic of function is not corresponding to its name
- my suggestions would be to change it to this -> const totalCapacity = getTotalCapacity(pool.Capacity) & calculation leave to the function

2021-07-01 16:42 UTC, MarcoMruz approved these changes

2021-07-02 07:48 UTC, merged