fix wf builder labels in edit modal
FRINXio/frinx-frontend pull request #1210
Opened 2023-04-14 13:54 UTC by plehocky

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-523` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  |

https://frinxhelpdesk.atlassian.net/browse/FD-523?atlOrigin=eyJpIjoiYzE4M2Q0YmVjMDdkNGI4ZGIzYjI2NjM5OTgzZTNkZDciLCJwIjoiaiJ9

labels of workflow were not shown when editing workflow via actions menu

HOW TO TEST
Open any workflow in edit mode, select actions and "Edit workflow". All labels that belong to the workflow should be visible and able to edit

2023-04-17 13:21 UTC, soson submitted a review, later dismissed

2023-04-24 18:49 UTC, Paulooze approved these changes

2023-04-25 10:52 UTC, MarcoMruz requested changes

2023-04-25 10:52 UTC, MarcoMruz commented on packages/frinx-workflow-builder/src/components/workflow-form/workflow-form.tsx
> +  }, []);
unnecessary use effect I recommend to remove it and add this logic inside directly in useTagsInput(<here>), and use IIFE function. Also add try catch block so that we can also handle if workflow-description is not JSON and in that case we will return just empty array. (to make this future proof)

`const tagsInput = useTagsInput(function() {
    try {
      return JSON.parse(workflow.description || '{}').labels || [];
    } catch (e) {
      return [];
    }
  }());` for example such as this code

2023-04-25 16:30 UTC, MarcoMruz approved these changes

2023-04-26 12:11 UTC, soson approved these changes

2023-04-26 12:12 UTC, merged