Wf builder support json and list input
FRINXio/frinx-frontend pull request #1211
Opened 2023-04-18 12:51 UTC by plehocky

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-512` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  |

https://frinxhelpdesk.atlassian.net/browse/FD-512?atlOrigin=eyJpIjoiYTRmOWE3NjdmMTQ5NGY4MWJhMzAyNjVjZGNjYzhjMGEiLCJwIjoiaiJ9

workflow inputs now wont stringify arrays and JSONs entered into input fields

HOW TO TEST
Click edit button of any workflow, click Save and Execute, fill out input fields with JSONs or arrays. Execute. In executed tab open the executed workflow and then Input/Output tab. JSONs and arrays shouldnt be stringified.

2023-04-19 12:44 UTC, Paulooze requested changes

2023-04-19 12:44 UTC, Paulooze commented on packages/frinx-workflow-ui/src/pages/executed-workflow-detail/executed-workflow-detail-tabs/input-output-tab.tsx
> +  const isJson = (data: string) => {
These functions don't need to inside the component.

2023-04-19 12:44 UTC, Paulooze commented on packages/frinx-workflow-ui/src/pages/executed-workflow-detail/executed-workflow-detail-tabs/input-output-tab.tsx
> +    if (Number(value)) {
`if (Number('0')) === false` - is this okay?

2023-04-19 12:44 UTC, Paulooze commented on packages/frinx-workflow-ui/src/pages/executed-workflow-detail/executed-workflow-detail-tabs/input-output-tab.tsx
> +  const replaceJsonAndArray = (key: string, value: string) => {
This seems overly complicated. Shouldn't just that one `isJson || Array.isArray` check be enough?

2023-04-25 10:53 UTC, MarcoMruz approved these changes

2023-04-26 12:17 UTC, soson approved these changes

2023-04-28 13:28 UTC, merged