Update rm v2.0
FRINXio/frinx-frontend pull request #1224
Opened 2023-05-29 10:28 UTC by plehocky

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-530` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  | No

https://frinxhelpdesk.atlassian.net/jira/software/c/projects/FD/boards/70?modal=detail&selectedIssue=FD-530

implemented changes in graphql data structure and filtering by allocated resources in RM

2023-05-31 11:23 UTC, MarcoMruz requested changes

2023-05-31 11:23 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/components/search-filter-pools-bar.tsx
> +  };
- do not use delete keyword
- try to define specific type for what values are we able to send in allocatedResourcesFilter
- when you want to clear values of those inputs just send empty value and do not remove it from the input (you will handle it in submit function when sendting request to server)

2023-05-31 11:23 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/nested-pools-detail-page/nested-pools-detail-page.tsx
>          setSearchText={setSearchText}
try to use two separate component for filtering because the component is gaining on unnecessary complexity

2023-06-09 04:20 UTC, MarcoMruz submitted a review, later dismissed

2023-06-09 12:50 UTC, soson commented on packages/frinx-resource-manager/src/components/search-by-allocated-resources.tsx
> +        delete updatedInputValues[propertyName];
dont mutate value with `delete` keyword

2023-06-12 07:47 UTC, MarcoMruz requested changes
you can simply use

`
return {
    ...prevInputValues,
    ...(value !== '' && {[propertyName]: value})
}
`

2023-06-12 07:54 UTC, soson commented on packages/frinx-resource-manager/src/pages/create-pool-page/create-pool-form-nested-part.tsx
> +                pool?.Resources !== undefined &&
is this check useful? 

if `pool?.Resources === undefined` it will fail on the first check `pool?.Resources.length`

2023-06-13 07:40 UTC, MarcoMruz approved these changes

2023-06-13 08:34 UTC, soson approved these changes

2023-06-13 08:47 UTC, merged