poll data refactoring to graphql
FRINXio/frinx-frontend pull request #1245
Opened 2023-07-18 09:58 UTC by plehocky

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-554` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  |

https://frinxhelpdesk.atlassian.net/jira/software/c/projects/FD/boards/70?modal=detail&selectedIssue=FD-554
refactored pollData to use graphql and added extended filtering options

2023-07-25 06:13 UTC, MarcoMruz requested changes

2023-07-25 06:13 UTC, MarcoMruz commented on packages/frinx-workflow-ui/src/pages/poll-data/poll-data.tsx
> +    afterDate: '' as string | undefined,
we do not use type assertions just to satisfy TS

2023-07-25 06:13 UTC, MarcoMruz commented on packages/frinx-workflow-ui/src/pages/poll-data/poll-data.tsx
> +  const [inputs, setInputs] = useState({
if you are using object for a state cleaner way would be to use type which will define what properties are we using and also if we will want to use this kind of object somewhere else

2023-07-25 06:13 UTC, MarcoMruz commented on packages/frinx-workflow-ui/src/pages/poll-data/poll-data.tsx
> +  }
function does not have to be in component move it outside or to helpers/utils file

2023-07-25 06:13 UTC, MarcoMruz commented on packages/frinx-workflow-ui/src/pages/poll-data/poll-data.tsx
> +    setFilter({});
if you are reseting value or object will not have any properties then set the value to null

2023-07-25 08:56 UTC, soson approved these changes

2023-07-25 10:36 UTC, soson approved these changes

2023-07-27 07:06 UTC, MarcoMruz approved these changes

2023-07-27 07:10 UTC, merged