Refactor event handlers
FRINXio/frinx-frontend pull request #1248
Opened 2023-07-24 14:52 UTC by MarcoMruz

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-536` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  |

- Refactored whole UI of event handler to support graphql
- created form to edit or create event handlers
- added filter searchbox to search for event handlers
- added detail page to look for more information about event handler

2023-08-01 10:17 UTC, soson requested changes

2023-08-01 10:17 UTC, soson commented on packages/frinx-workflow-ui/src/components/event-handler-form/event-handler-form.tsx
> +                values.actions.filter((_, i) => i !== index),
maybe more straightforward approch to delete item on index 
`[...values.actions].splice(index, 0)`

2023-08-01 10:24 UTC, soson requested changes
condition label is not properly vertically aligned in form

2023-08-03 08:08 UTC, soson approved these changes

2023-08-03 10:46 UTC, plehocky submitted a review, later dismissed

2023-08-03 14:22 UTC, soson approved these changes

2023-08-03 14:41 UTC, Paulooze approved these changes

2023-08-03 15:26 UTC, merged