Refactor pagination to shared folder
FRINXio/frinx-frontend pull request #1272
Opened 2023-08-16 06:42 UTC by plehocky

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-567` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  |

https://frinxhelpdesk.atlassian.net/browse/FD-567?atlOrigin=eyJpIjoiN2EyOTlhZDUyZWM3NGUwZGFiODA1NWZkYjdjNzgyN2EiLCJwIjoiaiJ9

moved pagination component and use pagination hook to shared folder and accordingly refactored its imports, then deleted redundant pagination files outside of shared folder. Also adjusted and unified look of pagination component so it would look the same in every component when used.

2023-08-16 14:26 UTC, MarcoMruz requested changes
Rewrite imports of frinx/shared/src to only frinx/shared

2023-08-16 14:26 UTC, MarcoMruz commented on packages/shared/src/components/pagination/pagination.tsx
> +    <Box my={4} px={4}>
why you do not use only m={4}?

2023-08-17 07:36 UTC, MarcoMruz submitted a review, later dismissed

2023-08-17 08:00 UTC, soson submitted a review, later dismissed

2023-08-17 10:55 UTC, MarcoMruz approved these changes

2023-08-17 12:32 UTC, soson approved these changes

2023-08-17 12:33 UTC, merged