FD-572 graph helpers fix
FRINXio/frinx-frontend pull request #1304
Opened 2023-08-28 07:32 UTC by soson

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-572` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  |

2023-08-30 08:33 UTC, MarcoMruz requested changes

2023-08-30 08:33 UTC, MarcoMruz commented on packages/shared/src/helpers/graph-to-api.helpers.ts
> +  const task = convertExtendedTaskToTask(unwrap(extendedTask));
this can cause white screen when extended task will be null or undefined... We should try it to handle it in trycatch and let know user there was a problem or to handle it in a way so that we remove null or undefined values

2023-09-04 09:02 UTC, Paulooze requested changes

2023-09-05 09:05 UTC, soson commented on packages/shared/src/helpers/graph-to-api.helpers.ts
> +  return omit(task, ['id', 'label']) as Task;
have no idea, how to properly fix it without `as Task`

2023-09-06 11:14 UTC, MarcoMruz approved these changes

2023-09-06 11:16 UTC, Paulooze approved these changes

2023-09-07 08:14 UTC, merged