Add sorting to rm
FRINXio/frinx-frontend pull request #1434
Opened 2023-09-22 12:53 UTC by plehocky

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-551` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  |

https://frinxhelpdesk.atlassian.net/jira/software/c/projects/FD/boards/77?modal=detail&selectedIssue=FD-551

test im RM -> pools page, click on either NAME or DEALOCATION SAFETY PERIOD in table head to sort

2023-09-22 13:42 UTC, MarcoMruz requested changes

2023-09-22 13:42 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/nested-pools-detail-page/nested-pools-detail-page.tsx
> +  const handleSort = (field: 'name' | 'dealocationSafetyPeriod') => {
use types provided by generated graphql types not your own, for future compatibility

2023-09-22 13:42 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/pools-page/pools-page.tsx
> +      resources: { [key: string]: string | null | undefined } | null | undefined;
why did you delete the defined type and rewritten it in here?

2023-09-22 13:42 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/pools-page/pools-page.tsx
> +  field: 'name' | 'dealocationSafetyPeriod';
as mentioned in the first comment

2023-09-26 04:29 UTC, MarcoMruz requested changes

2023-09-26 04:29 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/ipam-page/ipam-page.tsx
> +  const [allocatedResources, setAllocatedResources] = useState<{ [key: string]: string }>({});
use Record<string, string>

2023-09-26 04:29 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/pools-page/pools-page.tsx
> +type InputValues = { [key: string]: string | null | undefined };
same as above

2023-09-26 04:29 UTC, MarcoMruz commented on packages/frinx-resource-manager/src/pages/pools-page/pools-table.tsx
> +  onSort?: (sortKey: 'name' | 'dealocationSafetyPeriod') => void;
use generated type by graphql API, to future proof

2023-09-27 09:24 UTC, MarcoMruz approved these changes

2023-09-28 11:05 UTC, Paulooze approved these changes

2023-09-28 11:06 UTC, merged