Bulk install device inventory
FRINXio/frinx-frontend pull request #1440
Opened 2023-09-27 10:36 UTC by MarcoMruz

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-575` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  |

- add support for bulk device installation
- add helper function to prepare selected device id in format valid for graphql request
- add unit tests to control if helper function is working correctly

2023-10-02 07:17 UTC, Paulooze requested changes

2023-10-02 07:17 UTC, Paulooze commented on packages/frinx-inventory-client/api.graphql
> +  devicesToInstall: [Jozko!]!
`Jozko`?

2023-10-03 10:02 UTC, Paulooze approved these changes

2023-10-04 13:02 UTC, Paulooze approved these changes

2023-10-04 14:07 UTC, soson approved these changes

2023-10-04 16:24 UTC, merged