fixed workflow Save as
FRINXio/frinx-frontend pull request #1446
Opened 2023-10-03 07:49 UTC by plehocky

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-584` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  |

https://frinxhelpdesk.atlassian.net/jira/software/c/projects/FD/boards/77?modal=detail&selectedIssue=FD-584

fixed "Save as" button in action menu of workflow builder. When pressed and successful, it triggers toast notification and clones the WF with a new name

2023-10-03 10:01 UTC, Paulooze requested changes

2023-10-03 10:01 UTC, Paulooze commented on packages/frinx-workflow-builder/src/root.tsx
> +    const wfDetail = omit(workflowDetail, ['__typename']);
You don't really need `omit` for this. Something like:
```typescript
const { __typename, ...wfDetail } = workflowDetails;
```
is enough.

2023-10-04 10:02 UTC, soson approved these changes

2023-10-04 10:33 UTC, MarcoMruz approved these changes

2023-10-05 12:49 UTC, Paulooze approved these changes

2023-10-10 07:16 UTC, merged