inventoryWsURL change
FRINXio/frinx-frontend pull request #1506
Opened 2024-03-14 14:34 UTC by plehocky

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-X` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  |

Changes were made based on Jozefs request

2024-03-15 07:34 UTC, MarcoMruz requested changes
cannot we use env variable to set hostname? Is it needed to use window.location.hostname?

2024-03-15 08:56 UTC, MarcoMruz submitted a review, later dismissed

2024-03-18 13:21 UTC, soson approved these changes

2024-03-18 13:23 UTC, MarcoMruz approved these changes

2024-03-18 13:47 UTC, merged