create edit device form & page
FRINXio/frinx-frontend pull request #152
Opened 2021-09-06 15:12 UTC by MarcoMruz

2021-09-07 07:50 UTC, Paulooze requested changes
You should also add a way to actually get to the edit screen - add callback with redirect to "device list" (add an edit button next to config button that would get you to edit screen).

2021-09-07 07:50 UTC, Paulooze commented on packages/frinx-dashboard/src/inventory-app.tsx
> +import { EditDevicePage } from '@frinx/inventory-client/src';
Fix this import - you should import it the same way as other components.

2021-09-07 07:50 UTC, Paulooze commented on packages/frinx-dashboard/src/inventory-app.tsx
> +          path="/inventory/edit/:deviceId"
`/inventory/:deviceId/edit` looks better imo.

2021-09-07 07:53 UTC, soson commented on packages/frinx-inventory-client/src/pages/edit-device/edit-device-form.tsx
> +          Add device
Edit device

2021-09-07 07:54 UTC, soson commented on packages/frinx-inventory-client/src/pages/edit-device/edit-device-page.tsx
> +const ADD_DEVICE_MUTATION = gql`
UPDATE_DEVICE_MUTATION

2021-09-08 07:15 UTC, Paulooze requested changes

2021-09-08 07:15 UTC, Paulooze commented on packages/frinx-inventory-client/src/pages/device-list/device-table.tsx
> +                {isInstalled ? (
Could you explain this? First of all - it doesn't make any sense to have two ways to get to the edit screen (click on the name and click on the edit button). Second, you got it reversed - edit is only enabled when the device is not installed in UniConfig.

2021-09-08 07:15 UTC, Paulooze commented on packages/frinx-inventory-client/src/pages/device-list/device-table.tsx
> +                  isDisabled={!isInstalled}
Same as above - edit is enabled only when the device is NOT installed in UniConfig.

2021-09-10 08:50 UTC, Paulooze requested changes

2021-09-10 08:50 UTC, Paulooze commented on packages/frinx-inventory-client/src/pages/edit-device/edit-device-page.tsx
> +          title: 'Device succesfully added',
?

2021-09-10 08:50 UTC, Paulooze commented on packages/frinx-inventory-client/src/pages/device-list/device-table.tsx
> +                    variant="unstyled"
This button looks completely different to the other ones used in the table, why?

2021-09-10 08:50 UTC, Paulooze commented on packages/frinx-inventory-client/src/pages/edit-device/edit-device-form.tsx
> +  const INITIAL_VALUES = {
Use `useMemo` here, because this variable is gonna get "updated" every time this component is re-rendered

2021-09-10 08:50 UTC, Paulooze commented on packages/frinx-inventory-client/src/pages/edit-device/edit-device-page.tsx
> +        toast({
Use the new hook `useResponseToasts` - check device-list component.

2021-09-10 09:33 UTC, Paulooze approved these changes

2021-09-10 09:33 UTC, merged