fix-topology displaying redundant ports
FRINXio/frinx-frontend pull request #1538
Opened 2024-04-30 08:39 UTC by plehocky

| Q                        | A 
| ------------------------ | ---
| Fixed Issue?             | `FD-223` 
| Tests Added + Pass?      | Yes
| Any Dependency Changes?  |

https://frinxhelpdesk.atlassian.net/jira/software/c/projects/FD/boards/77?selectedIssue=FR-223
Only dots directly connected to selected device are now displayed when device is selected

2024-04-30 11:57 UTC, MarcoMruz requested changes

2024-04-30 11:57 UTC, MarcoMruz commented on packages/frinx-device-topology/src/components/node-icons/synce-node-icon.tsx
> +  selectedNode: GraphNode | GraphNetNode | PtpGraphNode | SynceGraphNode | null;
why do you need to define other types of grpah node when you are in synce-node-icon and other than SynceGraphNode is not able to send to this component. Same goes for other components

2024-05-03 09:15 UTC, MarcoMruz approved these changes

2024-05-03 10:38 UTC, soson approved these changes

2024-05-06 07:57 UTC, merged