create edit blueprint page
FRINXio/frinx-frontend pull request #160
Opened 2021-09-14 09:54 UTC by MarcoMruz

Created form & page for editing blueprint
Implemented in inventory-app

2021-09-14 10:02 UTC, Paulooze requested changes

2021-09-14 10:02 UTC, Paulooze commented on packages/frinx-inventory-client/src/pages/edit-blueprint/edit-blueprint-form.tsx
> +const blueprintSchema = yup.object({
None of those values is required - check `UpdateBlueprintInput` in the GraphQL schema.

2021-09-14 10:02 UTC, Paulooze commented on packages/frinx-inventory-client/src/pages/edit-blueprint/edit-blueprint-form.tsx
> +  initialValues: {
`initialValues: FormValues` ?

2021-09-14 10:15 UTC, MarcoMruz commented on packages/frinx-inventory-client/src/pages/edit-blueprint/edit-blueprint-form.tsx
> +const blueprintSchema = yup.object({
but if user deletes the name of blueprint than it will submit blueprint without name and it is not what we want am I right

2021-09-14 11:19 UTC, Paulooze commented on packages/frinx-inventory-client/src/pages/edit-blueprint/edit-blueprint-form.tsx
> +const blueprintSchema = yup.object({
`UpdateBlueprintInput` clearly states that both fields are optional - that's how updates work - if you don't send `name` it won't get updated. The Same applies to the `template` field.

2021-09-14 11:29 UTC, MarcoMruz commented on packages/frinx-inventory-client/src/pages/edit-blueprint/edit-blueprint-form.tsx
> +const blueprintSchema = yup.object({
I tried to remove name of blueprint & it removed name of blueprint so...

2021-09-14 12:04 UTC, MarcoMruz commented on packages/frinx-inventory-client/src/pages/edit-blueprint/edit-blueprint-form.tsx
> +const blueprintSchema = yup.object({
![Screenshot 2021-09-14 at 14 04 15](https://user-images.githubusercontent.com/51787428/133254317-76e1cb73-f82c-4221-a43a-cdee3bdbfd86.png)

2021-09-14 12:06 UTC, MarcoMruz commented on packages/frinx-inventory-client/src/pages/edit-blueprint/edit-blueprint-form.tsx
> +const blueprintSchema = yup.object({
So I need to handle if there is empty field then I only send filled fields, or it should be handled on BE?

2021-09-16 11:58 UTC, Paulooze approved these changes

2021-09-16 12:39 UTC, Paulooze approved these changes

2021-09-16 13:05 UTC, merged