Uniflow fix css, introduce chakra
FRINXio/frinx-frontend pull request #31
Opened 2021-02-22 08:42 UTC by JurajRusnak

2021-03-03 08:58 UTC, Paulooze requested changes

2021-03-03 08:58 UTC, Paulooze commented on packages/frinx-workflow-ui/src/pages/workflowList/WorkflowDefs/InputModal/InputModal.js
> +          <a style={{ float: 'left', marginRight: '50px' }} onClick={() => props.onWorkflowIdClick(wfId)}>
This definitely should be a button, not `a`.

2021-03-03 08:58 UTC, Paulooze commented on packages/frinx-workflow-ui/src/pages/workflowList/WorkflowListHeader.js
> +          <Button variant="outline" colorScheme="blue" onClick={onAddButtonClick}>
https://chakra-ui.com/docs/form/button#button-with-icon

2021-03-03 08:58 UTC, Paulooze commented on packages/frinx-workflow-ui/src/pages/workflowList/WorkflowDefs/WorkflowDefsReadOnly.js
>            <Typeahead
Wasn't the whole idea to get rid of bootstrap? Because this looks very weird right now.

2021-03-03 09:17 UTC, Paulooze commented
You should also try to rename all files and folders to follow our guidelines. However, be careful not to change just the letter casing (`Pagination.js` => `pagination.js`). Stuff like `InputModal.js` => `input-modal.js` is OK.

2021-03-09 15:20 UTC, ChmaraX commented
* Searching in "Poll data" crashed the page

* Please rename button label to something meaningful. It should inform that workflow is included in X other workflows as dependency, now it reads "Included in 1 Tree" which doesn't make sense. I would renaming to e.g. "X workflows" and adding tooltip on button that will say "Open dependeny tree" 
![image](https://user-images.githubusercontent.com/32128755/110488493-d049c780-80ee-11eb-81e3-31fda7edac90.png)

* I think it would be better to make labels/badges container wider, so its more horizontal than vertical, sacrificing space to right/left maybe making action buttons a bit smaller and/or making name/description less wide.
![image](https://user-images.githubusercontent.com/32128755/110488935-3e8e8a00-80ef-11eb-97cb-d0b685f05688.png)

It seems like it works in some cases when I type something in searchbar but then it probably resizes based on the highest row? 
![image](https://user-images.githubusercontent.com/32128755/110493499-f4a7a300-80f2-11eb-87b0-058710577852.png)

* Action buttons should be probably aligned to right
![image](https://user-images.githubusercontent.com/32128755/110489764-ee63f780-80ef-11eb-86b3-36f01b00ce0b.png)

* Clicking on favorite seems bugged - it puts favorite label but doesn't fill button icon
![image](https://user-images.githubusercontent.com/32128755/110490032-2f5c0c00-80f0-11eb-9f4b-c4b2780c7e26.png)

* Clicking on "Workflow List" button - modal seems to be too wide (it still uses semantic-ui or bootstrap classes)
![image](https://user-images.githubusercontent.com/32128755/110490382-8b269500-80f0-11eb-86fc-d32577a939e8.png)

* ![image](https://user-images.githubusercontent.com/32128755/110491018-2881c900-80f1-11eb-83f8-8c9620db6ff6.png)

* Tasks - Zoomed out to also capture pagination
![image](https://user-images.githubusercontent.com/32128755/110491275-6979dd80-80f1-11eb-96e8-0f412290f9ee.png)

* Needs wider modal + different pagination from other pages
![image](https://user-images.githubusercontent.com/32128755/110491427-90381400-80f1-11eb-876f-d09964409c9a.png)

* Missing "Rerun" button.
![image](https://user-images.githubusercontent.com/32128755/110491507-a514a780-80f1-11eb-997a-65a2743aa1b7.png)

* Different margin between search bar and table in EventListeners vs Tasks vs Polldata
![image](https://user-images.githubusercontent.com/32128755/110491764-e0af7180-80f1-11eb-9d35-040bee481265.png)
![image](https://user-images.githubusercontent.com/32128755/110491785-e5742580-80f1-11eb-9b6f-ee4e7ae5f0f7.png)

* Different table header sizes e.g. in Executed vs Others
![image](https://user-images.githubusercontent.com/32128755/110492198-426fdb80-80f2-11eb-85ee-e81e4620dc8d.png)
![image](https://user-images.githubusercontent.com/32128755/110492269-51ef2480-80f2-11eb-878e-0697ec5b22c6.png)

2021-03-16 08:47 UTC, Paulooze requested changes

2021-03-16 08:47 UTC, Paulooze commented on packages/frinx-workflow-ui/src/common/wf-autocomplete.js
> +        <Box bg="white" position="absolute" w="100%" zIndex="1000" border="1px solid #fafafa">
Use colors from the theme, not "magic" values (`zIndex` and `border`).

2021-03-16 08:48 UTC, Paulooze commented
![Screenshot 2021-03-16 at 09 36 39](https://user-images.githubusercontent.com/917323/111280874-9c195e00-863c-11eb-8c38-28ebcd374ae8.png)
Increase spacing between "arrows" and numbered buttons (same as the spacing between numbered buttons).

2021-03-16 08:48 UTC, Paulooze commented
![Screenshot 2021-03-16 at 09 37 12](https://user-images.githubusercontent.com/917323/111280998-c10dd100-863c-11eb-8d71-b1c759c5955c.png)
Make the buttons smaller, as this looks really weird.

2021-03-16 10:16 UTC, Paulooze approved these changes

2021-03-16 10:32 UTC, merged