service network form changes
FRINXio/frinx-frontend pull request #370
Opened 2022-01-26 08:57 UTC by soson

2022-01-26 14:38 UTC, Paulooze approved these changes

2022-01-31 09:47 UTC, Paulooze requested changes

2022-01-31 09:47 UTC, Paulooze commented on packages/frinx-gamma/src/components/forms/converters.ts
> +import { uniqueId } from 'lodash';
Can we use uuid as we use it everywhere for IDs?

2022-01-31 13:09 UTC, soson commented on packages/frinx-gamma/src/components/forms/converters.ts
> +import { uniqueId } from 'lodash';
resolved

2022-01-31 13:13 UTC, Paulooze approved these changes

2022-01-31 13:46 UTC, merged