Fd 322 executed page after bulk operations fix
FRINXio/frinx-frontend pull request #786
Opened 2022-07-12 12:14 UTC by filipvnencak

2022-07-12 12:35 UTC, MarcoMruz commented on packages/frinx-workflow-ui/src/pages/workflow-list/executed-workflow-list/executed-workflow-list.tsx
> +  const onSuccessfullDelete = () => {
handleOnSuccessfullDelete - as naming conventions suggests

2022-07-12 12:35 UTC, MarcoMruz commented on packages/frinx-workflow-ui/src/pages/workflow-list/executed-workflow-list/executed-workflow-list.tsx
> +        onSuccessfullDelete={onSuccessfullDelete}
rename function by the handler name

2022-07-12 12:36 UTC, MarcoMruz commented on packages/frinx-workflow-ui/src/pages/workflow-list/executed-workflow-list/executed-workflow-list.tsx
> +  };
this whole logic should be only once in component - as by DRY (don't repeat yourself) convention

2022-07-12 12:37 UTC, MarcoMruz commented on packages/frinx-workflow-ui/src/pages/workflow-list/executed-workflow-list/executed-workflow-list.tsx
> +  const onSuccessfullDelete = () => {
these are our conventions https://github.com/FRINXio/frinx-javascript

2022-07-14 06:17 UTC, MarcoMruz requested changes

2022-07-14 06:17 UTC, MarcoMruz commented on packages/frinx-workflow-ui/src/pages/workflow-list/executed-workflow-list/executed-workflow-list.tsx
> +    );
move this function out of component
- should return executed workflows

then you will call this function in handleOnSuccessfullOperation and also in useEffect (the one where fetchData function is). then you can set returned executedWorkflows with setPagination and setWorkflows functions

2022-07-14 14:07 UTC, MarcoMruz requested changes

2022-07-14 14:07 UTC, MarcoMruz commented on packages/frinx-workflow-ui/src/pages/workflow-list/executed-workflow-list/executed-workflow-list.tsx
> +const fetchData = async (state: StateProps, pagination: PaginationState) => {
rename to fetchExecutedWorkflows

2022-07-15 09:27 UTC, soson approved these changes

2022-07-15 10:27 UTC, closed without merging