Fix definitions pagination
FRINXio/frinx-frontend pull request #924
Opened 2022-10-06 08:41 UTC by MarcoMruz

FD 405

2022-10-06 08:43 UTC, Paulooze requested changes

2022-10-06 08:43 UTC, Paulooze commented on packages/frinx-workflow-ui/src/common/pagination-hook.ts
> +  haveCustomAmount: boolean;
`hasCustomAmount`?

2022-10-06 08:52 UTC, MarcoMruz commented on packages/frinx-workflow-ui/src/common/pagination-hook.ts
> +  haveCustomAmount: boolean;
yes, because when `items.length` is not actual total items length from which totalPages are calculated, you want to set length manually...

e.g. in executed workflows screen
executedWorkflow.length !== totalAmount of executedWorkflows

2022-10-06 10:16 UTC, Paulooze commented on packages/frinx-workflow-ui/src/common/pagination-hook.ts
> +  haveCustomAmount: boolean;
I meant that you should name it `has..` not `have...`

2022-10-10 09:10 UTC, Paulooze requested changes

2022-10-10 09:10 UTC, Paulooze commented on packages/frinx-workflow-ui/src/common/pagination-hook.ts
>  import * as React from 'react';
Can we be consistent with React imports? We usually do `import React, { ... } from 'react';`.

2022-10-10 09:54 UTC, Paulooze approved these changes

2022-10-10 09:56 UTC, merged