Merge create strat mutations
FRINXio/frinx-frontend pull request #938
Opened 2022-10-20 16:21 UTC by MarcoMruz

2022-10-21 08:41 UTC, Paulooze requested changes

2022-10-21 08:41 UTC, Paulooze commented on packages/frinx-uniresource-ui/src/components/expected-properties-form.tsx
> +const ExpectedProperties: FC<Props> = ({
This isn't `FC`? More like `VoidFunctionComponent`, right?

2022-10-21 08:41 UTC, Paulooze commented on packages/frinx-uniresource-ui/src/components/expected-properties-form.tsx
> +                //  @ts-ignore
What's with all these `@ts-ignore` comments? Fix it, or write a comment describing what's wrong.

2022-10-21 08:41 UTC, Paulooze commented on packages/frinx-uniresource-ui/src/components/expected-properties-form.tsx
> +          <HStack key={`expected-property-${index}`} my={3} align="flex-start">
You can use something like `poolProperty.key` instead of `index`, right? If key isn't unique, then composite key of `${poolProperty.key}${poolProperty.value}`.

2022-10-21 08:41 UTC, Paulooze commented on packages/frinx-uniresource-ui/src/pages/create-strategy-page/create-strategy-form.tsx
>      // @ts-ignore
Same as above - we shouldn't really use `@ts-ignore`.

2022-10-21 08:41 UTC, Paulooze commented on packages/frinx-uniresource-ui/src/pages/resource-types-page/create-resource-type-modal.tsx
> +// eslint-disable-next-line func-names
You don't really have to suppress this error like this, just name the function whatever.

2022-10-21 10:26 UTC, MarcoMruz commented on packages/frinx-uniresource-ui/src/components/expected-properties-form.tsx
> +          <HStack key={`expected-property-${index}`} my={3} align="flex-start">
key and values can also be same in som cases

2022-10-21 10:34 UTC, MarcoMruz commented on packages/frinx-uniresource-ui/src/components/expected-properties-form.tsx
> +          <HStack key={`expected-property-${index}`} my={3} align="flex-start">
and also keys and values are changing depending on input so then the fields are not updaing correspondingly to the values of fields

2022-10-21 14:44 UTC, Paulooze requested changes

2022-10-21 14:44 UTC, Paulooze commented on packages/frinx-uniresource-ui/src/components/expected-properties-form.tsx
> +          const expectedFieldError =
Move this to a function, it is too long/hard to read as a ternary - try to find a nice way with using `if`

2022-10-24 09:17 UTC, Paulooze requested changes

2022-10-24 09:17 UTC, Paulooze commented on packages/frinx-uniresource-ui/src/components/expected-properties-form.tsx
> +function getExpectedType<T>(value: unknown): T | null {
This function makes (almost) no sense - as soon as you use `as T`, typecheck becomes useless. What are you trying to achieve by this?

2022-10-24 09:17 UTC, Paulooze commented on packages/frinx-uniresource-ui/src/components/expected-properties-form.tsx
> +  const handleOnPoolPropertyAdd = () => onPropertyAdd([...expectedPropertyTypes, { key: '', type: '' }]);
Can we be consistent with arrow functions? Unless you want to specifically return the function, use `{}` as with the other functions in this component.

2022-10-24 09:17 UTC, Paulooze commented on packages/frinx-uniresource-ui/src/pages/create-strategy-page/create-strategy-form.tsx
> +          // @ts-ignore
Pretty sure we can get rid of this `@ts-ignore`.

2022-10-27 10:15 UTC, Paulooze requested changes

2022-10-27 10:15 UTC, Paulooze commented on packages/frinx-uniresource-ui/src/root.tsx
> +declare module 'yup' {
You should move this to a `.d.ts` file (next to tsconfig)

2022-11-02 09:11 UTC, Paulooze approved these changes

2022-11-02 09:47 UTC, merged