page reset on labels and keyword change
FRINXio/frinx-frontend pull request #983
Opened 2022-11-10 12:43 UTC by plehocky

Page resets to 1 when keyword or labels change - https://frinxhelpdesk.atlassian.net/browse/FD-409

2022-11-10 15:34 UTC, soson submitted a review, later dismissed

2022-11-10 21:17 UTC, MarcoMruz requested changes

2022-11-10 21:17 UTC, MarcoMruz commented on packages/frinx-workflow-ui/src/pages/workflow-list/workflow-definitions/workflow-definitions.tsx
> +  }, [keywords, labels]);
logic when we set current page to the first one I would move to the pagination hook... Because it is default logic for the hook so we do not have to implement it every time we use this hook in other places in the app

2022-11-10 21:17 UTC, MarcoMruz commented on packages/frinx-workflow-ui/src/pages/workflow-list/workflow-definitions/workflow-definitions.tsx
> +  }, [keywords, labels]);
look into `pagination-hook.tsx` there I would handle this logic

2022-11-11 11:11 UTC, MarcoMruz approved these changes

2022-11-11 11:12 UTC, merged